### PR TITLE
Further testing of GitHub Actions

### PR DESCRIPTION
**Pull request by rofreg**
Part of #321. Follow-up to PR #341.

In theory, opening this PR should cause [the `ci.yml` action](https://github.com/Sendouc/sendou.ink/actions/workflows/ci.yml) to run. Then we can see whether the GitHub Action actually works! Again, I suspect this will actually fail on first try 😛 

Once this is working and all the tests are passing, the [repo settings](https://github.com/rofreg/sendou.ink/settings) can be updated such that any merge into the `main` branch requires CI to pass.

### CODE REVIEW

**Comment by rofreg** [comment]
🎉 Looks like this sorta works! `plus.spec.ts` is broken, but `calendar.spec.ts` passes, so I think GitHub Actions is properly set up to boot the server and run Cypress 🚀

**Comment by Sendouc** [comment]
Oh this is really nice! 🚀 

Would it be possible to have it set up in a way where we can download fragments (screenshots / videos) of Cypress runs? The Plus Server functionality related tests work for me locally so I'd want to try to understand what is happening there.

As far as I can tell the only test that passes is just testing the lack of something so it might very well be a completely blank page passes even with the DB connection failing.

**Comment by rofreg** [comment]
It looks like it's possible for GitHub Actions to save artifacts after each run: https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts. I haven't done that before, but I'll give it try later today/this weekend.

Also your diagnosis sounds right to me, lol – maybe GitHub Actions isn't actually successfully starting the server yet. If so, screenshots / videos should be helpful to diagnose the problem!

**Comment by rofreg** [comment]
Cypress output is now being saved! (Click "Details" next to "CI / Cypress tests" below, and then click "Artifacts" in the upper-right of the page.)

It looks like `messages.js` is failing to load, though I'm not immediately sure why that's failing on GitHub Actions and working locally. I'll try a few things, but I might need help diagnosing the issue.

**Comment by rofreg** [comment]
Most tests are passing now! 🎉 I think the remaining failures may be legitimate test failures – if so, it might make sense to merge this PR as-is, and fix those issues in a separate PR.

**Comment by Sendouc** [comment]
Nice! 🎉 

Yeah made a separate issue for fixing the tests. Loading the files from JSON is not what the i18n we use recommends but as long as it works for now it's good enough. I need to switch out the lib to another one anyway (will detail this in another issue).

**Comment by Sendouc** [comment]
Had to revert this (check https://github.com/Sendouc/sendou.ink/pull/361 for details)

Not sure if I can actually reopen this PR or does there have to be a new PR?

Not 100% sure how we want to fix it. I suppose we could use `npm run compile && npm run dev` to start the app for tests? I will be replacing the i18n library asap since it is causing some severe problems but just to get this merged since having a pipeline like this is some good value.

**Comment by rofreg** [comment]
Ah, so sorry for the trouble! Reverting for now definitely makes sense – if there's a simple workaround to get the existing i18n working w/ GitHub Actions, that's probably a good place to start, and then we can always replace the i18n at a later time if desired.

**Pull request merged**
