### PR TITLE
Add "looking for individual coaching" and "looking for scrim partners" options

### PR DESCRIPTION
**Pull request by ximk**
Very simple change, just adds a new LFG type.

Addresses #1769.

### CODE REVIEW

**Comment by ximk** [comment]
@Sendouc Can you look into why this typecheck is failing? I've been searching for possible reasons for a bit and can't come up with a fix.

**Comment by Sendouc** [comment]
You need to modify the `LFGType` as defined in tables.ts :)

I would also get rid of this redundant constant on the file you modified. It should use the defined right under `LFGType` instead (`LFG_TYPES`)

**Comment by ximk** [comment]
This new error should be easier to fix, however I am lost again. 😅

**Comment by ximk** [comment]
Typecheck now passes thanks to @cysabi. :)

**Comment by ximk** [comment]
I'm going to add a "Looking for scrim partner" option as well, as I think that would be useful.

**Pull request merged**
