### PR TITLE
Clear weapon input on focus

### PR DESCRIPTION
**Pull request by DoubleCookies**
#1193 
`clearsInputOnFocus` already works in some other input fields and it's great! I guess how it works is enough for good experience with weapon selector.

### CODE REVIEW

**Comment by Sendouc** [comment]
Hmm from my testing it doesn't seem to work. It just clears the underlying value (what weapon is selected) but not the input's value (what user has typed). So maybe the whole prop is a bit bugged but yeah.

**Comment by DoubleCookies** [comment]
I guess it works same way as input in damage calc. I'll carefully check how it works.

**Comment by Sendouc** [comment]
I had so many problems with it before 😵 If it seems hard then dw about it or ask me for help!

**Comment by DoubleCookies** [comment]
I'll open it later if I find good solution

**Pull request closed without merging**
