### PR TITLE
upgrade to trpc 8

### PR DESCRIPTION
**Pull request by KATT**
- upgrade to trpc 8
- rename `ssr`-var to `ssg`
- enable batching

### CODE REVIEW

**Comment by Sendouc** [comment]
Hmm just getting the following error:

```
Error: Error serializing `.dehydratedState.queries[0].state.data[0].date` returned from `getStaticProps` in "/calendar".
Reason: `object` ("[object Date]") cannot be serialized as JSON. Please only return JSON serializable data types.
```

Any idea what could be going wrong here?

**Comment by KATT** [comment]
Can you tell me the steps on how to get the stuff / error running locally?

**Comment by KATT** [comment]
Might have fixed it now with `441ae33`

**Comment by Sendouc** [comment]
Hmm doesn't seem to sadly :( I will take a better look myself when I have a minute and if I can't figure it out I'll try to make an example you can run locally easily.

**Pull request closed without merging**
