### PR TITLE
Add badges for multiple tournaments

### PR DESCRIPTION
**Pull request by wooperissy**
PR on behalf of iliasDUDE for their tournament Get Coupled
https://discord.com/channels/299182152161951744/784073459516964954/1291016543764746323

### CODE REVIEW

**Comment by wooperissy** [comment]
I also added Pinch Zach's Bank by their request via DMs

**Comment by wooperissy** [comment]
I've also added a couple badges for Fry Basket on behalf of bluekin

**Comment by Sendouc** [comment]
pou does not have black background

**Comment by wooperissy** [comment]
oops I hadn't realised, should all be fixed now

**Comment by Sendouc** [comment]
Hmm aren't the rotation speeds off? the get coupled one seems to go much faster than the pou

**Comment by wooperissy** [comment]
oh yeah, that's a bit fast. I reached out to the artist and I'll remove it for now for the other 2 to get pushed through

**Comment by wooperissy** [comment]
if the other 2 are fine then this should be good to go, I'll submit a new PR when the other gets updated if needed

**Comment by Sendouc** [comment]
To my eye those have too low rotation speed. If you compare to some of the ones I just merged like https://github.com/Sendouc/sendou.ink/pull/1945

**Comment by wooperissy** [comment]
I think pou should match now, though I'm still waiting on PZB update

**Comment by wooperissy** [comment]
okay both should be fixed to match now!

**Pull request merged**
