### PR TITLE
Updated README with `npm run cf` steps & also a git command that will fix a line ending error

### PR DESCRIPTION
**Pull request by ElementUser**
Updated README with `npm run cf` steps & also a git command that will fix a line ending error

### CODE REVIEW

**Comment by ElementUser** [comment]
@remmycat after I investigated again, I tried committing those 63 changed or so files, only for Git to be smart & appear to reject my commit, but automatically fix the line endings. How strange...

I added the reference to help resolve this: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by ElementUser** [comment]
Anyway, I submitted a PR for your branch - so after accepting this one, you can merge your PR

**Comment by remmycat** [comment]
Awesome, thanks! Will merge this and check on the other PR if we need to consider something else. Maybe I'll laso add a link to the possibility with the local gitconfig. (I think that configuration is recommended on windows anyway)

And that's so weird with those 60 files, could you maybe just add a list/screenshot of which files? Like I wonder if it's files stylelint is that don't get formatted by prettier, but by stylelint or somethign.

**Comment by ElementUser** [comment]
In general, it's a weird behaviour if I don't change my autocrlf settings at all & I do something like `git reset --hard`, or I click on the button on Github where it updates my forked `rewrite` branch to the main one: 
image

In any case, I never ran `npm run cf` before until Sendou told me about it (at that time, it appears to have changed 400+ files). After I run the command I mentioned in the PR when I see this happens (`git add --renormalize .`), I don't encounter the issue again despite me not changing my line endings settings in the Git config.

I'll see if I can replicate the 63 files issue again - when I updated my rewrite branch on my fork to the main repo's btw, I see this:

image

Then when I attempt to run `npm run cf` again, I get 97 files unchanged:

image

`git status` shows:

```txt
        modified:   .eslintrc.js
        modified:   README.md
        modified:   app/components/Avatar.tsx
        modified:   app/components/Breadcrumbs.tsx
        modified:   app/components/BuildCard.tsx
        modified:   app/components/Combobox.tsx
        modified:   app/components/DateInput.tsx
        modified:   app/components/FormErrors.tsx
        modified:   app/components/MapPoolSelector.tsx
        modified:   app/components/icons/Globe.tsx
        modified:   app/components/icons/Moon.tsx
        modified:   app/components/icons/Sun.tsx
        modified:   app/components/icons/SunAndMoon.tsx
        modified:   app/components/layout/Footer.tsx
        modified:   app/components/layout/LanguageChanger.tsx
        modified:   app/components/layout/Menu.tsx
        modified:   app/components/layout/ThemeChanger.tsx
        modified:   app/components/layout/UserItem.tsx
        modified:   app/components/layout/index.tsx
        modified:   app/hooks/useTranslation.ts
        modified:   app/modules/i18n/config.ts
        modified:   app/modules/in-game-lists/gear-ids.ts
        modified:   app/modules/theme/action.server.ts
        modified:   app/modules/theme/provider.tsx
        modified:   app/modules/theme/session.server.ts
        modified:   app/root.tsx
        modified:   app/routes/a.tsx
        modified:   app/routes/analyzer.tsx
        modified:   app/routes/badges.tsx
        modified:   app/routes/badges/$id.tsx
        modified:   app/routes/builds.tsx
        modified:   app/routes/builds/$slug.tsx
        modified:   app/routes/builds/index.tsx
        modified:   app/routes/calendar/$id/index.tsx
        modified:   app/routes/calendar/$id/report-winners.tsx
        modified:   app/routes/calendar/components/Tags.tsx
        modified:   app/routes/calendar/index.tsx
        modified:   app/routes/calendar/new.tsx
        modified:   app/routes/contributions.tsx
        modified:   app/routes/faq.tsx
        modified:   app/routes/index.tsx
        modified:   app/routes/maps.tsx
        modified:   app/routes/object-damage-calculator.tsx
        modified:   app/routes/u.$identifier.tsx
        modified:   app/routes/u.$identifier/builds/index.tsx
        modified:   app/routes/u.$identifier/builds/new.tsx
        modified:   app/routes/u.$identifier/edit.tsx
        modified:   app/routes/u.$identifier/index.tsx
        modified:   app/routes/u.$identifier/results/components/UserResultsTable.tsx
        modified:   app/routes/u.$identifier/results/highlights.tsx
        modified:   app/routes/u.$identifier/results/index.tsx
        modified:   app/styles/calendar-new.css
        modified:   app/utils/dates.ts
        modified:   content/articles/ten-splatoon-tips.md
        modified:   public/locales/da/common.json
        modified:   public/locales/da/front.json
        modified:   public/locales/da/gear.json
        modified:   public/locales/de/common.json
        modified:   public/locales/de/gear.json
        modified:   public/locales/en/common.json
        modified:   public/locales/en/gear.json
        modified:   public/locales/es-ES/analyzer.json
        modified:   public/locales/es-ES/badges.json
        modified:   public/locales/es-ES/builds.json
        modified:   public/locales/es-ES/calendar.json
        modified:   public/locales/es-ES/common.json
        modified:   public/locales/es-ES/contributions.json
        modified:   public/locales/es-ES/faq.json
        modified:   public/locales/es-ES/front.json
        modified:   public/locales/es-ES/game-misc.json
        modified:   public/locales/es-ES/gear.json
        modified:   public/locales/es-ES/user.json
        modified:   public/locales/es-ES/weapons.json
        modified:   public/locales/es-US/analyzer.json
        modified:   public/locales/es-US/badges.json
        modified:   public/locales/es-US/builds.json
        modified:   public/locales/es-US/calendar.json
        modified:   public/locales/es-US/common.json
        modified:   public/locales/es-US/contributions.json
        modified:   public/locales/es-US/faq.json
        modified:   public/locales/es-US/front.json
        modified:   public/locales/es-US/game-misc.json
        modified:   public/locales/es-US/gear.json
        modified:   public/locales/es-US/user.json
        modified:   public/locales/es-US/weapons.json
        modified:   public/locales/fr/gear.json
        modified:   public/locales/it/gear.json
        modified:   public/locales/ja/gear.json
        modified:   public/locales/ko/gear.json
        modified:   public/locales/nl/gear.json
        modified:   public/locales/ru/gear.json
        modified:   public/locales/zh/gear.json
        modified:   scripts/create-analyzer-json.ts
        modified:   scripts/create-gear-json.ts
        modified:   scripts/create-misc-json.ts
        modified:   scripts/utils.ts
        modified:   translation-progress.md
```

So it seems like every time I update my fork's branch to the up-to-date main branch, any changed files get their line endings messed with. I could just update my git configs so it doesn't do this, but the whole reason why I brought up this behaviour in the first place is moreso for contributors that don't have a developer background & to make them not freak out if they see X files changed

**Comment by ElementUser** [comment]
Once again, `git add --renormalize .` seems to fix the line endings on all my files to be the same as the remote origin's & I get 0 unchanged files after running that command.

**Comment by remmycat** [comment]
Thanks a lot for the insights!

**Pull request merged**
