### PR TITLE
Add Rocket Science Badge

### PR DESCRIPTION
**Pull request by RileyStonesifer**
Updated .avif file re: previous pull request. My apologies, I am unfamiliar with github and making edits to the previous request, so I have resubmitted all changes (updated to the most recent fork).

### CODE REVIEW

**Comment by RileyStonesifer** [comment]
Badge artist is Riley Rooster

**Comment by Sendouc** [comment]
The rotation seems quite slow compared to existing badges, how does it seem to you?

**Comment by RileyStonesifer** [comment]
I see what you mean when I compare it with others on the site, but I'm not sure why. I did not tamper with any settings on the online viewer when creating the gif. Maybe my model is smaller than others used on the site and it has something to do with the rotation speed? 

I sped up the previous .gif file to more closely match the other badge rotation speeds visible on the site. 
rocket-science

If this new .gif file is suitable, let me know what needs to be done on my end to update my pull request (rather than delete and completely resubmit all of my changes). Again, I really apologize, I'm very unfamiliar with github.

**Comment by Sendouc** [comment]
All good no worries. But yeah that is still too slow. You can ask on the Discord channel for help. Just make a new one when you got it.

**Pull request closed without merging**
