### PR TITLE
Add E-liter badge

### PR DESCRIPTION
**Pull request by Akainacephalus**

### CODE REVIEW

**Comment by Sendouc** [comment]
.avif should be a static image (not animated)

**Comment by hfcRed** [comment]
Oh shoot that's my bad 😭

**Comment by Akainacephalus** [comment]
It should be fixed now, sorry

**Comment by Akainacephalus** [comment]
Nevermind I dont think I fixed it, I'll try again

**Comment by Akainacephalus** [comment]
I don't want to mess anything up so I'll just wait to see if I did it right or not

**Comment by Akainacephalus** [comment]
thank you! :)

**Pull request merged**
