### PR TITLE
Split ink vac sucking radius into min and max

### LINKED ISSUE #1820: Ink Vac sucking radius lists all labels on the Y axis
How it looks: 
image

It should look something more like:
image

### PR DESCRIPTION
**Pull request by Phil-hacker**
fixes #1820

### CODE REVIEW

**Comment by Phil-hacker** [comment]
translations are pulled from the `analyzer:damage.NORMAL_MIN` and `analyzer:damage.NORMAL_MIN` keys

**Comment by Phil-hacker** [comment]
@Sendouc is this looking good or should i change something?

**Comment by Sendouc** [comment]
Yep I think this is a good solution!

Omitting `roundToNDecimalPlaces` in the new version intentional? Makes the chart look a bit off maybe:

image

**Comment by Phil-hacker** [comment]
No, it wasn't intentional, just hadn't noticed it.

**Comment by Phil-hacker** [comment]
just fixed it

**Comment by Sendouc** [comment]
Thanks for the contribution :)

**Pull request merged**
